language: python
python:
	- 2.6
    - 2.7
    - 3.3
    - pypy
install:
    - pip install . coverage --use-mirrors
script:
    - coverage run --source tmdb -m py.test
after_success:
    - pip install coveralls --use-mirrors; coveralls
    - coverage report -m
